<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $book->name }} · Audiobook</title>
    <style>
        :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif}body{min-height:100vh;margin:0;color:#edf2ff;background:radial-gradient(circle at top left,#223b78,transparent 42%),#080d19}.listen{box-sizing:border-box;display:grid;min-height:100vh;place-items:center;padding:24px}.player{width:min(780px,100%);overflow:hidden;border:1px solid #304873;border-radius:20px;background:rgb(15 23 42/.92);box-shadow:0 28px 80px rgb(0 0 0/.36)}.cover{display:grid;min-height:210px;place-items:end start;padding:30px;background:linear-gradient(130deg,rgb(30 58 138/.8),rgb(14 116 144/.36)),#172554}.eyebrow{color:#c7dcff;font-size:.74rem;font-weight:750;letter-spacing:.1em;text-transform:uppercase}h1{max-width:620px;margin:9px 0 0;font-size:clamp(1.8rem,5vw,3rem);line-height:1.05}.body{display:grid;gap:22px;padding:26px 30px 30px}.meta,.track-label,.time{color:#b4c2dd}.meta{margin:0}.timeline{width:100%;accent-color:#70a2ff;cursor:pointer}.transport{display:flex;align-items:center;gap:15px}button,select{border:1px solid #405881;border-radius:10px;color:#eef4ff;background:#1d2a43;font:inherit;cursor:pointer}button{min-width:96px;padding:11px 14px;font-weight:700}button:hover{background:#2a3c60}.play{border-color:#5c91ff;background:#3978ff}.play:hover{background:#4b86fa}.time{min-width:86px;font-size:.85rem;text-align:right}.mix{display:flex;flex-wrap:wrap;gap:8px;align-items:center;border-top:1px solid #29405f;padding-top:18px}.track{display:flex;align-items:center;gap:7px;padding:7px 9px;border-radius:9px;background:#16233a;font-size:.82rem}.track input{width:70px;accent-color:#70a2ff}.speed{margin-left:auto;display:flex;gap:7px;align-items:center;color:#b4c2dd;font-size:.82rem}select{padding:6px}@media(max-width:540px){.listen{padding:0}.player{min-height:100vh;border:0;border-radius:0}.cover{min-height:250px}.body{padding:22px}.speed{margin-left:0}}
    </style>
</head>
<body><main class="listen"><section class="player" aria-label="Audiobook player"><header class="cover"><div><span class="eyebrow">Audiobook release · v{{ $release->version_number }}</span><h1>{{ $book->name }}</h1></div></header><div class="body"><p class="meta">{{ $release->label ?: 'Audiobook release' }} · {{ sprintf('%d:%02d', intdiv($release->duration_ms, 60000), intdiv($release->duration_ms, 1000) % 60) }}</p><input class="timeline" id="progress" aria-label="Listening progress" type="range" min="0" max="1000" value="0"><div class="transport"><button class="play" id="play" type="button">Play</button><span class="time" id="time">0:00 / {{ sprintf('%d:%02d', intdiv($release->duration_ms, 60000), intdiv($release->duration_ms, 1000) % 60) }}</span></div><div class="mix">@foreach($tracks as $track => $url)<label class="track"><span class="track-label">{{ strtoupper($track) }}</span><input class="channel-volume" data-track="{{ $track }}" aria-label="{{ $track }} volume" type="range" min="0" max="100" value="100"></label>@endforeach<label class="speed">Speed <select id="speed" aria-label="Playback speed"><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label></div></div></section></main>
<script>
const urls=@json($tracks),audio=Object.fromEntries(Object.entries(urls).map(([key,url])=>[key,new Audio(url)])),voice=audio.voice,play=document.querySelector('#play'),progress=document.querySelector('#progress'),time=document.querySelector('#time'),format=seconds=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`,sync=target=>Object.values(audio).forEach(item=>{if(item!==target&&Math.abs(item.currentTime-target.currentTime)>.12)item.currentTime=target.currentTime});play.addEventListener('click',async()=>{if(voice.paused){await Promise.all(Object.values(audio).map(item=>item.play().catch(()=>null)));play.textContent='Pause'}else{Object.values(audio).forEach(item=>item.pause());play.textContent='Play'}});voice.addEventListener('timeupdate',()=>{progress.value=voice.duration?Math.round(voice.currentTime/voice.duration*1000):0;time.textContent=`${format(voice.currentTime)} / ${format(voice.duration||{{ $release->duration_ms / 1000 }})}`;sync(voice)});voice.addEventListener('ended',()=>{Object.values(audio).forEach(item=>{item.pause();item.currentTime=0});play.textContent='Play'});progress.addEventListener('input',()=>{const next=(voice.duration||0)*Number(progress.value)/1000;Object.values(audio).forEach(item=>item.currentTime=next)});document.querySelector('#speed').addEventListener('change',event=>Object.values(audio).forEach(item=>item.playbackRate=Number(event.target.value)));document.querySelectorAll('.channel-volume').forEach(input=>input.addEventListener('input',()=>audio[input.dataset.track].volume=Number(input.value)/100));
</script></body></html>
