import '../../../css/bookDistribution.css';
import { bookPanelButton } from '../shared/bookPanelButton';
const providers = _.rod([]), readiness = _.rod({}), loading = _.rod(true), status = _.rod(null), activeType = _.rod('all');
const typeOptions = [{ value: 'all', label: 'All channels' }, { value: 'ebook', label: 'eBooks' }, { value: 'print', label: 'Print' }, { value: 'audiobook', label: 'Audiobooks' }];
const keyBook = (ctx) => ctx?.params?.key_book || window.location.pathname.match(/\/dashboard\/book\/([^/]+)\/distribution/)?.[1] || null;
const dataOf = (payload) => payload?.data?.data || payload?.data || payload || {};
async function load(key) { loading.value = true; try { const data = dataOf(await _.http.getJSON(`/dashboard/api/books/${encodeURIComponent(key)}/distribution`)); CMSwift.reactive.untracked(() => { providers.value = data.providers || []; readiness.value = data.readiness || {}; }); } catch (error) { status.value = { type: 'danger', message: error.message || 'Unable to load distribution channels.' }; } finally { loading.value = false; } }
const icon = (provider) => provider.types.includes('audiobook') ? 'headphones' : provider.types.includes('print') ? 'menu_book' : 'auto_stories';
function connect(key, provider) { const label = _.rod(provider.connection.account_label || ''), token = _.rod(''), saving = _.rod(false), dialogStatus = _.rod(null), requiresApi = provider.connection_mode !== 'manual'; const save = async (close) => { saving.value = true; dialogStatus.value = null; try { const data = dataOf(await _.http.putJSON(`/dashboard/api/books/${encodeURIComponent(key)}/distribution/${provider.key}`, { account_label: label.value.trim() || null, api_token: token.value.trim() || null })); providers.value = providers.value.map(item => item.key === provider.key ? { ...item, connection: data.connection } : item); status.value = { type: 'success', message: `${provider.name} connection saved.` }; close(); } catch (error) { dialogStatus.value = { type: 'danger', message: error.message || 'Unable to save this connection.' }; } finally { saving.value = false; } }; _.Dialog({ size: 'md', stickyActions: true, slots: { header: _.div(_.h3(`Connect ${provider.name}`), _.span({ class: 'text-muted' }, provider.note)), content: ({ close }) => _.div({ class: 'at-distributionDialog' }, _.Input({ label: 'Account label', model: label, placeholder: 'e.g. My publishing account' }), requiresApi ? _.Input({ label: provider.connection_mode === 'aggregator' ? 'API token (optional)' : 'API token', type: 'password', model: token, placeholder: provider.connection.has_token ? 'Leave empty to keep saved token' : 'Paste provider API token' }) : _.div({ class: 'at-distributionManual' }, _.Icon({ name: 'open_in_new' }), _.span('This provider uses its own publishing portal. Save the account label to track the release here, then use the export files in that portal.')), () => dialogStatus.value ? _.Alert(dialogStatus.value) : null, _.div({ class: 'at-distributionDialogActions' }, _.Btn({ color: 'secondary', onClick: close }, 'Cancel'), _.Btn({ color: 'primary', icon: 'link', loading: saving, onClick: () => save(close) }, requiresApi ? 'Save connection' : 'Mark ready'))) } }).open(); }
async function disconnect(key, provider) { if (!window.confirm(`Disconnect ${provider.name}?`)) return; try { await _.http.delJSON(`/dashboard/api/books/${encodeURIComponent(key)}/distribution/${provider.key}`); providers.value = providers.value.map(item => item.key === provider.key ? { ...item, connection: { status: 'not_connected' } } : item); } catch (error) { status.value = { type: 'danger', message: error.message || 'Unable to disconnect this channel.' }; } }
function card(provider, key) { const linked = provider.connection.status !== 'not_connected'; return _.article({ class: `at-distributionProvider ${linked ? 'is-connected' : ''}` }, _.div({ class: 'at-distributionProviderHead' }, _.span({ class: 'at-distributionProviderIcon' }, _.Icon({ name: icon(provider) })), _.div(_.strong(provider.name), _.small(provider.types.map(type => type === 'ebook' ? 'eBook' : type === 'audiobook' ? 'Audiobook' : 'Print').join(' · '))), _.span({ class: `at-distributionState ${provider.connection.status}` }, !linked ? 'Not connected' : provider.connection.status === 'manual_ready' ? 'Ready to publish' : 'Connected')), _.p(provider.note), _.div({ class: 'at-distributionProviderActions' }, !linked ? _.Btn({ color: 'primary', icon: 'link', onClick: () => connect(key, provider) }, provider.connection_mode === 'manual' ? 'Set up' : 'Connect') : [_.Btn({ dense: true, color: 'secondary', icon: 'settings', onClick: () => connect(key, provider) }, 'Manage'), _.Btn({ dense: true, color: 'danger', icon: 'link_off', title: 'Disconnect', onClick: () => disconnect(key, provider) })])); }
export default function bookDistribution(ctx) { const key = keyBook(ctx); load(key); window.AudiobookTools?.setPageHeaderActions?.([bookPanelButton(key)]); return _.main({ class: 'at-distributionPage' }, _.section({ class: 'at-distributionHeader' }, _.div(_.span('Distribution hub'), _.h2('Publish everywhere'), _.p('Prepare direct and aggregator channels for eBooks, print editions and audiobooks.')), _.Btn({ color: 'secondary', icon: 'refresh', onClick: () => load(key) }, 'Refresh')), () => status.value ? _.Alert(status.value) : null, () => loading.value ? _.div({ class: 'at-distributionLoading' }, 'Loading distribution workspace…') : _.div({ class: 'at-distributionWorkspace' }, _.section({ class: 'at-distributionReadiness' }, _.div(_.span('Release readiness'), _.h3('Files available for distribution')), _.div({ class: 'at-distributionReadinessItems' }, [['auto_stories', 'ePub', readiness.value.epub], ['picture_as_pdf', 'Print PDF', readiness.value.pdf], ['headphones', 'Audiobook', readiness.value.audiobook], ['image', 'Cover', readiness.value.cover]].map(([name, label, ready]) => _.div({ class: ready ? 'is-ready' : 'is-missing' }, _.Icon({ name }), _.span(label), _.small(ready ? 'Ready' : 'Missing'))))), _.section({ class: 'at-distributionChannels' }, _.div({ class: 'at-distributionChannelsHead' }, _.div(_.span('Connected storefronts'), _.h3('Distribution channels')), _.Select({ model: activeType, options: typeOptions })), () => _.div({ class: 'at-distributionGrid' }, providers.value.filter(provider => activeType.value === 'all' || provider.types.includes(activeType.value)).map(provider => card(provider, key)))))); }
