import '../../../css/statistics.css';
const report=_.rod(null),loading=_.rod(true),status=_.rod(null),period=_.rod('90');
const unwrap=p=>p?.data?.data||p?.data||p||{}; const eur=c=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format((c||0)/100);
async function load(){loading.value=true;try{report.value=unwrap(await _.http.getJSON(`/dashboard/api/statistics?period=${period.value}`));}catch(e){status.value={type:'danger',message:e.message||'Unable to load earnings statistics.'};}finally{loading.value=false;}}
const money=(icon,value,label,note)=>_.div({class:'at-statMoney'},_.Icon({name:icon}),_.div(_.strong(()=>eur(value())),_.span(label),_.small(note)));
function payoutDialog(){_.Dialog({size:'sm',slots:{header:_.div(_.span('Payouts'),_.h3('Set up withdrawals'),_.p('A verified payment provider is required before withdrawals can be requested.')),content:({close})=>_.div({class:'at-statDialog'},_.Icon({name:'account_balance'}),_.p('Payouts are not connected yet. No withdrawal request has been created.'),_.Btn({color:'secondary',onClick:close},'Close'))}}).open();}
function bookTable(items){return _.div({class:'at-statTable'},...items.map(b=>_.div({class:'at-statRow'},_.div({class:'at-statBook'},b.cover_img?_.img({src:b.cover_img,alt:''}):_.Icon({name:'menu_book'}),_.strong(b.name)),_.span(`${b.plays} plays`),_.span(`${eur(b.revenue_per_play_cents)} / play`),_.strong(eur(b.revenue_cents)))));}
function payoutTable(items){return _.div({class:'at-statTable'},...items.map(p=>_.div({class:'at-statRow'},_.span(p.status),_.span(p.paid_at?new Date(p.paid_at).toLocaleDateString():'Awaiting processing'),_.strong(eur(p.amount_cents)))));}
export default function statisticsPage(){load();return _.main({class:'at-statPage'},_.section({class:'at-statHero'},_.div(_.span('Financial analytics'),_.h2('Earnings & payouts'),_.p('See the revenue reported by each publication channel and keep payout status in one place.')),_.Btn({color:'primary',icon:'account_balance',onClick:payoutDialog},'Withdraw funds')),()=>status.value?_.Alert(status.value):null,()=>{if(loading.value)return _.div({class:'at-statLoading'},'Loading earnings…');if(!report.value)return null;const r=report.value,books=r.books||[],payouts=r.payouts||[];return _.div({class:'at-statWorkspace'},_.section({class:'at-statFilters'},_.Select({label:'Reporting period',model:period,options:[{value:'28',label:'Last 28 days'},{value:'90',label:'Last 90 days'},{value:'365',label:'Last 12 months'}],onChange:load}),_.small('Revenue is shown only when reported by a connected distribution provider.')),_.section({class:'at-statCards'},money('payments',()=>r.summary.gross_cents,'Gross earnings','Selected period'),money('account_balance_wallet',()=>r.summary.available_cents,'Available to withdraw','After recorded payouts'),money('south_east',()=>r.summary.pending_cents,'Pending payouts','Processing or pending'),money('check_circle',()=>r.summary.paid_cents,'Paid out','Completed withdrawals')),_.section({class:'at-statBooks'},_.div({class:'at-statHead'},_.div(_.span('Catalogue revenue'),_.h3('Earnings by book')),_.small('Sorted by reported revenue')),books.length?bookTable(books):_.div({class:'at-statEmpty'},_.Icon({name:'payments'}),_.span('No books are available yet.'))),_.section({class:'at-statPayouts'},_.div({class:'at-statHead'},_.div(_.span('Payout history'),_.h3('Withdrawals')),_.small('Verified transfers only')),payouts.length?payoutTable(payouts):_.div({class:'at-statEmpty'},_.Icon({name:'history'}),_.div(_.strong('No payouts yet'),_.span('Connect a verified payout provider before requesting your first withdrawal.')))));});}
