<?php

return [
    'image_model' => env('AT_OPENAI_IMAGE_MODEL', 'gpt-image-1'),

    'defaults' => [
        [
            'provider_key' => 'mock',
            'name' => 'AT · Test mode',
            'base_url' => null,
            'models' => ['mock-correction-v1', 'mock-translation-v1'],
            'default_model' => 'mock-correction-v1',
            'connection_mode' => 'managed',
            'api_provider' => 'mock',
            'supports_background_jobs' => false,
            'is_configured' => true,
            'billing_label' => 'Test mode · no credits',
            'privacy_label' => 'No external AI request is made.',
        ],
        [
            'provider_key' => 'at-openai',
            'name' => 'AT · OpenAI',
            'base_url' => 'https://api.openai.com/v1',
            'models' => ['gpt-5-mini', 'gpt-5', 'gpt-4.1-mini'],
            'default_model' => 'gpt-5-mini',
            'connection_mode' => 'managed',
            'api_provider' => 'openai',
            'managed_api_key' => env('AT_OPENAI_API_KEY'),
            'supports_background_jobs' => true,
            'is_configured' => filled(env('AT_OPENAI_API_KEY')),
            'billing_label' => 'Audiobook Tools credits',
            'privacy_label' => 'Your manuscript is processed by Audiobook Tools through OpenAI.',
            'translation_credits_per_1000_words' => [
                'gpt-5-mini' => 1,
                'gpt-5' => 4,
                'gpt-4.1-mini' => 1,
            ],
        ],
        [
            'provider_key' => 'at-anthropic',
            'name' => 'AT · Anthropic',
            'base_url' => 'https://api.anthropic.com',
            'models' => ['claude-sonnet-4', 'claude-haiku-3.5'],
            'default_model' => 'claude-sonnet-4',
            'connection_mode' => 'managed',
            'api_provider' => 'anthropic',
            'supports_background_jobs' => true,
            'is_configured' => false,
            'billing_label' => 'Audiobook Tools credits',
            'privacy_label' => 'Coming soon.',
        ],
        [
            'provider_key' => 'openai',
            'name' => 'Personal · OpenAI',
            'base_url' => 'https://api.openai.com/v1',
            'models' => ['gpt-5-mini', 'gpt-5', 'gpt-4.1-mini'],
            'default_model' => 'gpt-5-mini',
            'connection_mode' => 'byok',
            'api_provider' => 'openai',
            'supports_background_jobs' => false,
            'is_configured' => true,
            'billing_label' => 'Your OpenAI account',
            'privacy_label' => 'Your encrypted API key is used for interactive requests only.',
        ],
        [
            'provider_key' => 'anthropic',
            'name' => 'Personal · Anthropic',
            'base_url' => 'https://api.anthropic.com',
            'models' => ['claude-sonnet-4', 'claude-haiku-3.5'],
            'default_model' => 'claude-sonnet-4',
            'connection_mode' => 'byok',
            'api_provider' => 'anthropic',
            'supports_background_jobs' => false,
            'is_configured' => true,
            'billing_label' => 'Your Anthropic account',
            'privacy_label' => 'Your encrypted API key is used for interactive requests only.',
        ],
        [
            'provider_key' => 'google',
            'name' => 'Personal · Google Gemini',
            'base_url' => 'https://generativelanguage.googleapis.com',
            'models' => ['gemini-2.5-flash', 'gemini-2.5-pro'],
            'default_model' => 'gemini-2.5-flash',
            'connection_mode' => 'byok',
            'api_provider' => 'google',
            'supports_background_jobs' => false,
            'is_configured' => true,
            'billing_label' => 'Your Google account',
            'privacy_label' => 'Your encrypted API key is used for interactive requests only.',
        ],
        [
            'provider_key' => 'openrouter',
            'name' => 'Personal · OpenRouter',
            'base_url' => 'https://openrouter.ai/api/v1',
            'models' => ['openai/gpt-5-mini', 'anthropic/claude-sonnet-4'],
            'default_model' => 'openai/gpt-5-mini',
            'connection_mode' => 'byok',
            'api_provider' => 'openrouter',
            'supports_background_jobs' => false,
            'is_configured' => true,
            'billing_label' => 'Your OpenRouter account',
            'privacy_label' => 'Your encrypted API key is used for interactive requests only.',
        ],
        [
            'provider_key' => 'ollama',
            'name' => 'Local · Ollama',
            'base_url' => 'http://127.0.0.1:11434',
            'models' => ['llama3.1', 'mistral', 'qwen2.5'],
            'default_model' => 'llama3.1',
            'connection_mode' => 'local',
            'api_provider' => 'ollama',
            'supports_background_jobs' => false,
            'is_configured' => true,
            'billing_label' => 'Your local infrastructure',
            'privacy_label' => 'The server must be reachable from this Audiobook Tools installation.',
        ],
    ],
];
